### ISSUE TITLE
docker-compose and dummy dataset of products/items

### ISSUE THREAD

**Issue by lucmichalski** [zhenghaoz/gorse#112]
Hi @zhenghaoz ,

Hope you are all well !

I am posting this issue as I was wondering if it could be possible to add a docker-compose file for bootstrapping gorse with all its components ?

Also, I was wondering if you could provide a dummy dataset of products (e-commerce) to show case how to import and query for collaborative filtering scores. If you want, I can create such dataset if you give me the columns definition of the csv or jsonl file. :-)

Thanks for any insights or inputs on these questions.

Cheers,
Luc Michalski

**Comment by zhenghaoz** [comment]
Hi @lucmichalski 

Thanks for your suggestion. I will create docker-compose file and dummy datasets ASAP.

**Comment by lucmichalski** [comment]
Thanks :-)

If you want I can give you a large scale dataset (anonymized) from an e-commerce store (prestashop based)

**Comment by zhenghaoz** [comment]
> Thanks :-)
> 
> If you want I can give you a large scale dataset (anonymized) from an e-commerce store (prestashop based)

FYI, [docker-compose.yml](https://github.com/zhenghaoz/gorse/blob/master/docker/docker-compose.yml). However, it's hard to prepare a full featured dataset, it needs more time. If you'd like to contribute your dataset, share to me please. :D

**Comment by lucmichalski** [comment]
do you have an email address ? or a telegram account, mine is "deepocrates"

**Comment by zhenghaoz** [comment]
example dataset has been update via #130 : https://cdn.gorse.io/example/github.sql
