### ISSUE TITLE
执行gorse-cli cluster  server节点都会增加一个

### ISSUE THREAD

**Issue by ouyangzhongmin** [zhenghaoz/gorse#121]
![image](https://user-images.githubusercontent.com/7018141/116048975-5b374f00-a6a8-11eb-8cdf-a158d80cd00e.png)
![image](https://user-images.githubusercontent.com/7018141/116049556-ff20fa80-a6a8-11eb-9f40-9e0b18dcaffe.png)

每次执行gorse-cli cluster  server节点都会增加一个呢？ docker-compose启动的，windows10系统

**Comment by zhenghaoz** [comment]
[release-0.2](https://github.com/zhenghaoz/gorse/tree/release-0.2) 解决了这个问题，合并后不会有这个问题啦

**Comment by ouyangzhongmin** [comment]
> [release-0.2](https://github.com/zhenghaoz/gorse/tree/release-0.2) 解决了这个问题，合并后不会有这个问题啦

什么时候发布release-0.2呢

**Comment by zhenghaoz** [comment]
最近在开发GUI，合并就去我就打算标记一个0.2版本

GUI：https://github.com/gorse-io/dashboard

**Comment by zhenghaoz** [comment]
0.2.0-release 中已经解决
