### ISSUE TITLE
访问http://127.0.0.1:8087/apidocs/失败

### ISSUE THREAD

**Issue by ouyangzhongmin** [zhenghaoz/gorse#125]
![image](https://user-images.githubusercontent.com/7018141/116358187-f0188480-a82f-11eb-9192-89d2be3b59bb.png)
docker启动

![image](https://user-images.githubusercontent.com/7018141/116358289-0fafad00-a830-11eb-93c5-c359059ef23d.png)
docker-compose配置:
![image](https://user-images.githubusercontent.com/7018141/116358696-82208d00-a830-11eb-9f2c-053e1d426382.png)

**Comment by zhenghaoz** [comment]
奇怪了，我并没有复现成功，你的操作系统和浏览器是什么

**Comment by ouyangzhongmin** [comment]
windows10， googlechrome浏览器

**Comment by zhenghaoz** [comment]
修复已经合并
