### ISSUE TITLE
用户反馈记录里如何记录用户的评分值？

### ISSUE THREAD

**Issue by ouyangzhongmin** [zhenghaoz/gorse#126]
![image](https://user-images.githubusercontent.com/7018141/116661189-a7df9a80-a9c6-11eb-8bc2-06873d85f825.png)
根据数据库表结构用户反馈记录只能记录用户行为，但是评分值是如何录入的呢？

**Comment by zhenghaoz** [comment]
目前版本只会记录用户正反馈（喜欢、点赞、收藏）和负反馈（已读），通过`positive_feedback_types`确定正反馈。评分预测目前算法层面不支持，因为数据库也就没支持了。

**Comment by ouyangzhongmin** [comment]
好的，感谢！
