### ISSUE TITLE
请问是否有实现物品相似度计算呢

### ISSUE THREAD

**Issue by ouyangzhongmin** [zhenghaoz/gorse#131]
比如根据电影的属性和标签计算一个电影相似的推荐列表

**Comment by zhenghaoz** [comment]
/api/dashboard/neighbors/{item-id}

这个接口可以返回和物品相关度最高的其他物品，依据是共同用户数量。至于标签和属性的相似度的话，目前还没有实现。

**Comment by ouyangzhongmin** [comment]
目前的neighbors接口实现确实不是我需要的，期待基于属性的相似度接口加入！
