### ISSUE TITLE
请问系统可以在windows上用么

### ISSUE THREAD

**Issue by dotcool** [zhenghaoz/gorse#14]
如题

**Comment by zhenghaoz** [comment]
纯Go语言编写的应用程序理论上是跨平台的，不过我没有仔细调试过，至于到底可不可以，我还需要自己试一下再告诉你😄

**Comment by dotcool** [comment]
![image](https://user-images.githubusercontent.com/6111056/55781652-439ac700-5add-11e9-9316-d21c0b6c7496.png)

我直接这边这样执行，出现错误了。

请问readme里面的方法，怎么执行呢

**Comment by dotcool** [comment]
@zhenghaoz 我想做一个类似今日头条的那种推荐，根据用户的兴趣，用你这个可以实现么

**Comment by zhenghaoz** [comment]
1. README里面是我写错了，不知道这样可以不可以
```bash
git clone https://github.com/zhenghaoz/gorse.git
cd gorse
go build cmd/gorse.go
```
2. 如果你要做一个比较简易的推荐系统，那么是可以用这个系统来做的，但是如果对于推荐效果很在意，那么这个引擎给出的推荐是比较粗糙的。另外，我的实现里面还有很多需要优化的地方，内存使用上有些问题。

**Comment by dotcool** [comment]
![image](https://user-images.githubusercontent.com/6111056/55797166-52de3c80-5afe-11e9-87c2-b9fd016a242e.png)
不行呢，会提示这个错误。

我们对推荐的效果要求不是很高，只是想根据用户的数据，比如点击量或者阅读时间来实时的更改推荐列表，也就是实时推荐。我们系统是用go来实现所以我找了下大概就你这个挺好的呢。

**Comment by zhenghaoz** [comment]
要不您试一下我在[README中更新的方法](https://github.com/zhenghaoz/gorse#install)

如果数据量比较小，可以尝试本项目生成一些候选的项目，然后再做一些处理（常见的是结合CTR预测）还是可以的。^_^

**Comment by dotcool** [comment]
nice可以跑起来
