### ISSUE TITLE
Neighbors endpoint in apidocs not functioning.

### ISSUE THREAD

**Issue by andy-igoo** [zhenghaoz/gorse#141]
In `http://127.0.0.1:8087/apidocs/` using an ID from an import of the github.sql tutorial the url generated doesn't seem to be correct and returns an empty json. It is making it uncertain as to what endpoint to use:

Example: 
Item ID of `007:hashcash-js` results in:

`http://127.0.0.1:8087/api/neighbors/{item-id}?item-id=007%3Ahashcash-js`

![Selection_517](https://user-images.githubusercontent.com/37870907/119449291-61adfa80-bd2a-11eb-8c4a-5ee6b194c461.png)

**Comment by zhenghaoz** [comment]
What about `http://127.0.0.1:8087/api/neighbors/007:hashcash-js`? Actually, `{item-id}` is the path parameter.
