### ISSUE TITLE
我执行第二步，导入数据

### ISSUE THREAD

**Issue by dotcool** [zhenghaoz/gorse#16]
./gorse data root:password@/edu --import-ratings-csv import_ratings.csv --import-items-csv import_items.csv

使用了example里面的csv，但是提示错误

Error 1148: The used command is not allowed with this MySQL version

能告知一下mysql的版本么

**Comment by zhenghaoz** [comment]
这是因为MySQL默认禁用了`LOAD LOCAL INFILE`命令的权限，可以尝试[打开权限](https://stackoverflow.com/questions/12819098/error-1148-mysql-the-used-command-is-not-allowed-with-this-mysql-version)

**Comment by dotcool** [comment]
非常感谢，解决了。
