### ISSUE TITLE
LightFM a hybrid recommendation algorithm. 

### ISSUE THREAD

**Issue by deslum** [zhenghaoz/gorse#17]
maybe heard about LightFM?

https://github.com/lyst/lightfm

**Comment by zhenghaoz** [comment]
Yes. It's a good idea to utilize metadata using factorization machine. Maybe it could be implemented one day.

**Comment by mrtztg** [comment]
LightFM is such a great library.
I hope to add similar features to Gorse.

**Comment by zhenghaoz** [comment]
Factorization machines have been integerated as an online recommendation model (see https://gorse.io/en/docs/ch01-01-principle.html#ranking-mechanism).
