### ISSUE TITLE
Recommend new relevant products based on historical transaction records

### ISSUE THREAD

**Issue by hetao29** [zhenghaoz/gorse#178]
In a business scenario, for user historical transactions, or sold out items, to recommend new items on the shelves can be based on feedback or labels.

In other words, for some items, participate in the calculation, but not participate in the recommendation.

**Comment by hetao29** [comment]
棒！

**Comment by zhangzhenghao** [comment]
> 棒！

master分支还不能用，缓存刷新还需要优化，需要等0.3发布哈
