### ISSUE TITLE
unknown command "init" for "gorse"

### ISSUE THREAD

**Issue by Heisenbilin** [zhenghaoz/gorse#18]
我的gorse.exe里面并没有init命令，也没有找到相应的sql文件

**Comment by zhenghaoz** [comment]
不好意思，我文档没有更新，用SQL数据库保存数据速度较慢，现在已经替换成嵌入数据库了，如果您要尝试的话，可能要稍等一下了。

**Comment by Heisenbilin** [comment]
好的，麻烦你了，我会等待你的更新

**Comment by zhenghaoz** [comment]
我已经更新了readme，你可以试一下啦😁

**Comment by Heisenbilin** [comment]
谢谢你！我正在尝试跟随你的wiki来了解你的系统，想问一下你的wiki内容是最新的吗？

**Comment by zhenghaoz** [comment]
并不是哦，还在补充之中😁

获取 Outlook for Android<https://aka.ms/ghei36>

________________________________
