### ISSUE TITLE
Looks like most of documentation is deleted 

### ISSUE THREAD

**Issue by ThomasMeetKai** [zhenghaoz/gorse#180]
There is only one chapter open at docs.gorse.io, but there are links to other chapters that return 404's.

For example, this page: https://docs.gorse.io/ch01-02-architect.html
Links to this page: https://docs.gorse.io/ch02-03-api.html

But that page doesn't exist.

**Comment by zhenghaoz** [comment]
I am rewriting documents these days 😂. There are pages haven't been finished.

**Comment by outranker** [comment]
> I am rewriting documents these days 😂. There are pages haven't been finished.

Is it also possible to add more explanations and descriptions? I would really appreciate it ~
Keep up the good work!

**Comment by zhenghaoz** [comment]
Hi, @ThomasMeetKai @outranker, documents https://docs.gorse.io/ have been update. If you want to know more information, feel free to contact me.
