### ISSUE TITLE
请问是否可以支持自定义？

### ISSUE THREAD

**Issue by andyzhou** [zhenghaoz/gorse#19]
你好，大神：
在单机测试了下你做的这个项目，挺不错的。👍
现在我几个问题想请教下，先谢谢了。
1. 可以自定义数据结构么，目前项目是基于rate以及关联item进行推荐。有没有可能不仅仅基于rate，比如用户在某个内容发表评论、点赞、打标签等等这些指标呢？
2. 看了下api.go，里面有两个数据录入接口/items和/feedback，是需要json根式的数据么，大概样式是什么样的呢？
3. 在测试/random/?number=3的时候，返回结果有时少于3个。
4. 如果把数据存在mongo db里，是否需要自己用代码实现？

再次感谢分享这个项目👍

**Comment by zhenghaoz** [comment]
你好，感谢对本项目的支持

1. 项目中SVD(BPR)模型是支持没有评分的交互记录的，例如评论、点赞、打标签等等，也就是用户有没有做某个动作，这个时候无视评分即可。另外，如果某个动作带有权重，可以使用WRMF，将权重作为rating进行预测，例如玩游戏的时长、看电影的时长等等。
2. API接口可以参考文档中的[API](https://gorse.readthedocs.io/en/latest/usage/server/api.html)一节；
3. 这是个实现的BUG，我之前也发现了，看来是时候修复它了；
4. 如果想把数据存在mongdb里面，那么需要自己实现一个和mongdb交互的组件，也就是实现[database.go](https://github.com/zhenghaoz/gorse/blob/master/engine/database.go)中的的接口。

实在抱歉，文档还在更新当中，有些地方可能会表述不清楚。

**Comment by andyzhou** [comment]
感谢大神回复，还有几个问题想请教下。
1. 关于第一个问题，不知道我理解的对不对。比如点赞场景，我将{"UserId":2048,"ItemId":1000,"Rating":0}这样的数据通过/feedback接口发送到推荐系统里么？还是通过其他方式进行操作呢？
2. 在现有项目的数据结构里，如果需要额外增加字段，比如用户行为里增加一个关键字、标签等，可以直接扩展到现有结构么？还是需要在代码中增加相关字段呢？
3. 一个item的rate分，现有系统支持运行时动态更新么? 比如透过api直接修改rate分值。

**Comment by zhenghaoz** [comment]
1. 是的，就是这样，可以忽略评分`{"UserId":2048,"ItemId":1000}`；
2. 系统内部存储就是采用类似NoSQL的形式，因此底层是支持的，但是目前系统里现成的算法无法利用这些信息，因此我没有加入；
3. 目前还不能，但是添加这个功能还是方便的，而且我也觉得很有必要；
4. 目前还不能，这个功能需要改动比较大了，但是想想你的建议。
