### ISSUE TITLE
Error in example

### ISSUE THREAD

**Issue by deslum** [zhenghaoz/gorse#2]
Error in example

```
package main

import (
	"fmt"
	"github.com/zhenghaoz/gorse/base"
	"github.com/zhenghaoz/gorse/core"
	"github.com/zhenghaoz/gorse/model"
)

func main() {
	// Load dataset
	data := core.LoadDataFromBuiltIn("ml-100k")
	// Split dataset
	train, test := core.Split(data, 0.2)
	// Create model
	svd := model.NewSVD(base.Params{
		base.Lr:       0.007,
		base.NEpochs:  100,
		base.NFactors: 80,
		base.Reg:      0.1,
	})
	// Fit model
	svd.Fit(train)
	// Evaluate model
	fmt.Printf("RMSE = %.5f\n", core.RMSE(svd, test))
	// Predict a rating
	fmt.Printf("Predict(4,8) = %.5f\n", svd.Predict(4, 8))
}package main

import (
	"fmt"
	"github.com/zhenghaoz/gorse/base"
	"github.com/zhenghaoz/gorse/core"
	"github.com/zhenghaoz/gorse/model"
)

func main() {
	// Load dataset
	data := core.LoadDataFromBuiltIn("ml-100k")
	// Split dataset
	train, test := core.Split(data, 0.2)
	// Create model
	svd := model.NewSVD(base.Params{
		base.Lr:       0.007,
		base.NEpochs:  100,
		base.NFactors: 80,
		base.Reg:      0.1,
	})
	// Fit model
	svd.Fit(train)
	// Evaluate model
	fmt.Printf("RMSE = %.5f\n", core.RMSE(svd, test))
	// Predict a rating
	fmt.Printf("Predict(4,8) = %.5f\n", svd.Predict(4, 8))
}
```

> ./main.go:25:39: not enough arguments in call to core.RMSE
> 	have (*model.SVD, *core.DataSet)
> 	want (core.Model, *core.DataSet, *core.DataSet)

**Comment by zhenghaoz** [comment]
:smile: Thanks for your feedback. The "real" example is [example/get_starrted/main.go](https://github.com/zhenghaoz/gorse/blob/master/example/get_starrted/main.go). The README file is a little bit out-of-date and I have updated it in the latest commit 26024cb0203d218a8672c98f7d22955fc93575a5.

**Comment by deslum** [comment]
what is the last parameter in function core.RMSE?

**Comment by zhenghaoz** [comment]
The last parameter is reserved for the training set, which is necessary for top N evaluation (ratings in the training set should be excluded). However, this parameter is useless for rating prediction evaluator and could be set to `nil`. The current evaluator interface is so ugly so I have changed it in 7807a25902a8ca8291eaed9a621aa7e2d95d2456 of `dev` branch.

**Comment by deslum** [comment]
thanks
