### ISSUE TITLE
Recommendation for skeleton problem

### ISSUE THREAD

**Issue by fire** [zhenghaoz/gorse#200]
Hi,

I want to build a system similar to https://blog.unity.com/technology/mecanim-humanoids.

Inputs:

1. 3d Mesh data of the vertices
5. 3d Mesh data loop edge length of the mesh for the waist for example
6. 3d Mesh data vertex weighting
2. skeleton bone
3. skeleton bone names
4. skeleton bone parentage
4. skeleton bone transforms

Outputs:

1. match an existing skeleton bone by slot aka "Recommend a skeleton slot."

Would this system be a good match?

**Comment by zhenghaoz** [comment]
I am afraid that the skeleton problem can't be handled by a traditional recommender system. In normal recommender system, users don't have restrictions on recommended items or users only have simple queries.     In the skeleton problem, 3D mesh data is hard to be utilized.

**Comment by fire** [comment]
Thanks.
