### ISSUE TITLE
在Ubuntu18.04上go get命令报错

### ISSUE THREAD

**Issue by Arithmeticjia** [zhenghaoz/gorse#21]
root@VM-0-16-ubuntu:~# go get github.com/zhenghaoz/gorse/...
# go.etcd.io/bbolt
/home/go/src/go.etcd.io/bbolt/bolt_unix_aix.go:13:59: flock redeclared in this block
	previous declaration at /home/go/src/go.etcd.io/bbolt/bolt_unix.go:13:59
/home/go/src/go.etcd.io/bbolt/bolt_unix_aix.go:46:22: funlock redeclared in this block
	previous declaration at /home/go/src/go.etcd.io/bbolt/bolt_unix.go:45:22
/home/go/src/go.etcd.io/bbolt/bolt_unix_aix.go:56:27: mmap redeclared in this block
	previous declaration at /home/go/src/go.etcd.io/bbolt/bolt_unix.go:50:27
/home/go/src/go.etcd.io/bbolt/bolt_unix_aix.go:76:21: munmap redeclared in this block
	previous declaration at /home/go/src/go.etcd.io/bbolt/bolt_unix.go:72:21
root@VM-0-16-ubuntu:~# cd /usr/local/go
root@VM-0-16-ubuntu:/usr/local/go# go get github.com/zhenghaoz/gorse/...
# go.etcd.io/bbolt
/home/go/src/go.etcd.io/bbolt/bolt_unix_aix.go:13:59: flock redeclared in this block
	previous declaration at /home/go/src/go.etcd.io/bbolt/bolt_unix.go:13:59
/home/go/src/go.etcd.io/bbolt/bolt_unix_aix.go:46:22: funlock redeclared in this block
	previous declaration at /home/go/src/go.etcd.io/bbolt/bolt_unix.go:45:22
/home/go/src/go.etcd.io/bbolt/bolt_unix_aix.go:56:27: mmap redeclared in this block
	previous declaration at /home/go/src/go.etcd.io/bbolt/bolt_unix.go:50:27
/home/go/src/go.etcd.io/bbolt/bolt_unix_aix.go:76:21: munmap redeclared in this block
	previous declaration at /home/go/src/go.etcd.io/bbolt/bolt_unix.go:72:

请教下如何安装gorse，不胜感激

**Comment by zhenghaoz** [comment]
BoltDB已经在v1.3.3中修复了这个问题（ etcd-io/bbolt#160 ），我会更新一下BoltDB版本
