### ISSUE TITLE
worker error"failed to decode click model"

### ISSUE THREAD

**Issue by lbw114007** [zhenghaoz/gorse#214]
error log info:

{"level":"error","ts":1627382137.876585,"caller":"worker/worker.go:256","msg":"failed to decode click model","error":"EOF","stacktrace":"github.com/zhenghaoz/gorse/worker.(*Worker).Pull\n\t/home/runner/work/gorse/gorse/worker/worker.go:256"}

**Comment by outranker** [comment]
when i was spinning up gorse for the first time using docker-compose, this error log showed up. i think it was because there was no data in the db. dumping some data and then restarting containers solved the issue for me

**Comment by zhenghaoz** [comment]
> when i was spinning up gorse for the first time using docker-compose, this error log showed up. i think it was because there was no data in the db. dumping some data and then restarting containers solved the issue for me

Thanks for your reply. ❤️

**Comment by lbw114007** [comment]
> when i was spinning up gorse for the first time using docker-compose, this error log showed up. i think it was because there was no data in the db. dumping some data and then restarting containers solved the issue for me

Thanks,my question has been solved.

**Comment by zhenghaoz** [comment]
The issues will be closed since this bug has been fix by #224 .
