### ISSUE TITLE
failed to run with Docker Compose

### ISSUE THREAD

**Issue by akchain** [zhenghaoz/gorse#215]
Hi, thanks for your great work. 
I got following error messages when try to run gorse with docker compose. How to fix it? thanks.
![image](https://user-images.githubusercontent.com/71252184/127285626-af4419a2-7ac3-4266-afd6-e2317195bae9.png)

**Comment by zhenghaoz** [comment]
This happens when a worker or server starts up earlier than the master. This error will disappear when the master starts.
