### ISSUE TITLE
redis password support?

### ISSUE THREAD

**Issue by lbw114007** [zhenghaoz/gorse#216]
password is required for online redis service.

**Comment by zhenghaoz** [comment]
Could you help to add password support? Just use [ParseURL](https://pkg.go.dev/github.com/go-redis/redis/v8#ParseURL) to parse `path` as `*redis.Options` here:

https://github.com/zhenghaoz/gorse/blob/aa0632d8715b36c9afdd353e1703400667b5b74e/storage/cache/database.go#L103
