### ISSUE TITLE
请问如何在mac上运行？

### ISSUE THREAD

**Issue by Arithmeticjia** [zhenghaoz/gorse#22]

**Comment by Arithmeticjia** [comment]
在bin下面生成了一个gorse的可执行文件，但是在终端输入gorse还是显示没有这个命令

**Comment by zhenghaoz** [comment]
bin文件夹有没有添加到环境变量`PATH`？另外也可以考虑下载编译好的二进制文件:smile:：https://github.com/zhenghaoz/gorse/releases。
