### ISSUE TITLE
how to trigger model training

### ISSUE THREAD

**Issue by outranker** [zhenghaoz/gorse#223]
first of all, thank you for implementing this amazing recommendation engine!
we are planning to implement gorse in our app which is similar to social networking apps

i have 2 questions about manually refreshing recommendation cache and triggering model training i.e generating new recommendations.
1. in our app, users can change their profile status to private and when they do so all their items (feed images in our app) also become private. we need to avoid recommending them to other users. is it possible to trigger model training and generating new recommendation list when user changes profile status to private? we already tweaked the code to our needs for this action but wondering how we could go about manually starting generating new recommendations
2. i am guessing if we want to exclude private items from recommendations we also need to update cache since in cache previous recommendation list are stored. if we trigger new action to generate recommendation list would all the cache be rewritten (not include private items), how do we update redis cache when change happens?

these are the changes we made:
1. when gorse pulls data from database, it only pulls public users and items
2. when user changes their profile, update user status and batch update user items in database

**Comment by zhenghaoz** [comment]
Hi, @outranker. Maybe you want a `IsHidden` option for users and items. Is it right? When a item is hidden, it won't be recommended to users anymore.

**Comment by outranker** [comment]
> Hi, @outranker. Maybe you want a `IsHidden` option for users and items. Is it right? When a item is hidden, it won't be recommended to users anymore.

Hello ~
Yes, that is close to what i was thinking about. In our case, the user is hidden and all the items belonging to that user is hidden as well. But since in gorse, there is not item vs item owner relationship, we can think of it item being hidden

**Comment by zhenghaoz** [comment]
Okay, it seems quite similar to #178. I will try to address it in a future version.
