### ISSUE TITLE
how do I set the X-API-Key?

### ISSUE THREAD

**Issue by anphy** [zhenghaoz/gorse#229]
I noticed the "secret key for RESTful API" in swagger UI, but I cant find where to set it?

**Comment by zhenghaoz** [comment]
You could set it in configuration file:

https://github.com/zhenghaoz/gorse/blob/f9f9a389a2a5871dd694334d14c309fb9b2dc64d/config/config.toml.template#L52

**Comment by anphy** [comment]
> You could set it in configuration file:
> 
> https://github.com/zhenghaoz/gorse/blob/f9f9a389a2a5871dd694334d14c309fb9b2dc64d/config/config.toml.template#L52

tks
