### ISSUE TITLE
Strings for user and item IDs

### ISSUE THREAD

**Issue by robertbakker** [zhenghaoz/gorse#23]
Hi there,

Currently it is not possible to use User IDs other than integers,
for example `8b3876c0-69b5-444e-9118-c5fcd575169f`, cannot be converted with `str.Atoi()`, which results in an error.

Is it possible to support strings for IDs? 

Cheers,

**Comment by zhenghaoz** [comment]
Thanks for your feedback. The string type seems more general. I will make it work but need some time. :smile:

**Comment by zhenghaoz** [comment]
The issue has been addressed by #24 .
