### ISSUE TITLE
A question: I cant set redis db_number in the config file

### ISSUE THREAD

**Issue by anphy** [zhenghaoz/gorse#230]
As  the title showed, If I set a db_number for redis in the config.toml file, I would get an error msg from the server:"dial tcp: address tcp/6379/1: unknown port".

**Comment by zhenghaoz** [comment]
Could you show me your DSN of Redis? I will investigate on it later.

**Comment by anphy** [comment]
> Could you show me your DSN of Redis? I will investigate on it later.

redis://localhost:6379

**Comment by zhenghaoz** [comment]
Hi, @anphy. I tried `cache_store = "redis://localhost:6379/1"` in my configuration and there is no problem.

**Comment by anphy** [comment]
> Hi, @anphy. I tried `cache_store = "redis://localhost:6379/1"` in my configuration and there is no problem.

Can you try inserting a feedback with api and see what the sever will print?

**Comment by zhenghaoz** [comment]
This issue seems irreproducible. Feel free to reopen it if you need more help.
