### ISSUE TITLE
Error 1064: SQL syntax error on loading feedback csv

### ISSUE THREAD

**Issue by avinashkurup** [zhenghaoz/gorse#231]
Hi,
    I get this error while loading the feedback as csv file in the Gorse console, could you help me with this. Please let me know if you need any more information.

Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'AS new ON DUPLICATE KEY UPDATE time_stamp = new.time_stamp, `comment` = new.`com' at line 1

Thanks,
Avinash.

**Comment by zhenghaoz** [comment]
Could you paste the first line of your CSV file? Or could you show the screen shot of feedback import page.

**Comment by hetao29** [comment]
I have the same issue.

**Comment by hetao29** [comment]
https://github.com/zhenghaoz/gorse/pull/249 fixed.
