### ISSUE TITLE
Tasks not running in web UI.

### ISSUE THREAD

**Issue by avinashkurup** [zhenghaoz/gorse#236]
Hi,

I loaded the csv data into the console, I use the configuration defined here, https://docs-cn.gorse.io/ch01-03-config.html

I do not get any recommendations in the UI, also could you tell me how the tasks updated will be displayed in the UI, I at the moment see this,

![Capture](https://user-images.githubusercontent.com/681657/129711314-7408d7e0-c66b-4bdf-aa09-f0f2ec3f34bf.PNG)

Please help me in understanding if tasks are to be configured, for them to run on the nodes.

Thanks,
Avinash.

**Comment by zhenghaoz** [comment]
It seems you are stucked on using Gorse. Maybe you could discuss with us on Discord: https://discord.gg/x6gAtNNkAE
