### ISSUE TITLE
pq: sorry, too many clients already

### ISSUE THREAD

**Issue by rinshadka** [zhenghaoz/gorse#248]
Hi,
I have updated my gorse version to latest **v0.2.5**, along with the latest config.toml . Now we are getting below error after the application runs for few time:-

```
{"level":"error","ts":1631013939.8973596,"caller":"server/rest.go:1252","msg":"internal server error","error":"pq: sorry, too many clients already","errorVerbose":"pq: sorry, too many clients already\n/go/gorse/storage/data/sql.go:226: ","stacktrace":"github.com/zhenghaoz/gorse/server.internalservererror\n\t/go/gorse/server/rest.go:1252\ngithub.com/zhenghaoz/gorse/server.(*restserver).getmeasurements\n\t/go/gorse/server/rest.go:1234\ngithub.com/emicklei/go-restful/v3.(*filterchain).processfilter\n\t/go/pkg/mod/github.com/emicklei/go-restful/v3@v3.5.2/filter.go:21\ngithub.com/zhenghaoz/gorse/server.logfilter\n\t/go/gorse/server/rest.go:71\ngithub.com/emicklei/go-restful/v3.(*filterchain).processfilter\n\t/go/pkg/mod/github.com/emicklei/go-restful/v3:1932"}
{"level":"info","ts":1631013939.897418,"caller":"server/rest.go:74","msg":"GET /api/measurements/ClickThroughRate?n=30","status_code":500}
```

I have used the docker implementation with Postgres as backend database.
Thanks.

**Comment by rinshadka** [comment]
> 
> 
> Hi,
> I have updated my gorse version to latest **v0.2.5**, along with the latest config.toml . Now we are getting below error after the application runs for few time:-
> 
> ```
> {"level":"error","ts":1631013939.8973596,"caller":"server/rest.go:1252","msg":"internal server error","error":"pq: sorry, too many clients already","errorVerbose":"pq: sorry, too many clients already\n/go/gorse/storage/data/sql.go:226: ","stacktrace":"github.com/zhenghaoz/gorse/server.internalservererror\n\t/go/gorse/server/rest.go:1252\ngithub.com/zhenghaoz/gorse/server.(*restserver).getmeasurements\n\t/go/gorse/server/rest.go:1234\ngithub.com/emicklei/go-restful/v3.(*filterchain).processfilter\n\t/go/pkg/mod/github.com/emicklei/go-restful/v3@v3.5.2/filter.go:21\ngithub.com/zhenghaoz/gorse/server.logfilter\n\t/go/gorse/server/rest.go:71\ngithub.com/emicklei/go-restful/v3.(*filterchain).processfilter\n\t/go/pkg/mod/github.com/emicklei/go-restful/v3:1932"}
> {"level":"info","ts":1631013939.897418,"caller":"server/rest.go:74","msg":"GET /api/measurements/ClickThroughRate?n=30","status_code":500}
> ```
> 
> I have used the docker implementation with Postgres as backend database.
> Thanks.

I have found many queries like below in **idle state** which checking pg_stat_activilty

```
16384 | gorse_db |   51 |            |       10 | gorse   |                  | 172.19.0.2  |                 |       53132 | 2021-09-07 14:56:23.418783+00 |
              | 2021-09-07 15:39:28.975199+00 | 2021-09-07 15:39:28.975218+00 | Client          | ClientRead          | idle   |             |              | SELECT COALESCE(
AVG(user_ctr),0) FROM (SELECT COUNT(positive_feedback.user_id) :: DOUBLE PRECISION / COUNT(read_feedback.user_id) :: DOUBLE PRECISION AS user_ctr FROM (SELECT DISTINCT user_i
d, item_id FROM feedback WHERE DATE(time_stamp) = DATE($1) AND feedback_type IN ($2,$3)) AS positive_feedback RIGHT JOIN (SELECT DISTINCT user_id, item_id FROM feedback WHERE
 DATE(time_stamp) = DATE($4) AND feedback_type = $5) AS read_feedback ON positive_feedback.user_id = read_feedback.user_id AND positive_feedback.item_id = read_feedback.item_
id GROUP BY read_feedback.user_id HAVING COUNT(positive_feedback.user_id) > 0) AS user_ctr | client backend
```

**Comment by zhenghaoz** [comment]
I will try to reproduce it. 😅

**Comment by ccfish86** [comment]
Is the `result:  sql.Rows` not close was not exec. in cases like below?
![image](https://user-images.githubusercontent.com/15622514/133773407-3cac4660-9246-48c6-bccc-9e4699bc8fc2.png)

**Comment by zhenghaoz** [comment]
> Is the `result: sql.Rows` not close was not exec. in cases like below?
> ![image](https://user-images.githubusercontent.com/15622514/133773407-3cac4660-9246-48c6-bccc-9e4699bc8fc2.png)

It make sense. Thank you 😂
