### ISSUE TITLE
CSV导入中文会出现乱码

### ISSUE THREAD

**Issue by amaaazing** [zhenghaoz/gorse#250]
// 修改点：函数入参签名 sep 类型：uint8 -> string
func ReadLines(sc *bufio.Scanner, sep string, handler func(int, []string) bool) error {
	lineCount := 0               // line number of current position
	fields := make([]string, 0)  // fields for current line
	builder := strings.Builder{} // string builder for current field
	quoted := false              // whether current position in quote
	for sc.Scan() {
		// read line
		lineStr := sc.Text()
		// golang中string底层是通过byte数组实现的。
		// 中文字符在unicode下占2个字节，在utf-8编码下占3个字节，而golang默认编码正好是utf-8
		// 将string转成rune类型,
		line := []rune(lineStr)
		// start of line
		if quoted {
			builder.WriteString("\r\n")
		}
		// parse line
		for i := 0; i < len(line); i++ {
			// 直接判断分隔符
			if string(line[i]) == sep && !quoted {
				// end of field
				fields = append(fields, builder.String())
				builder.Reset()
			} else if line[i] == '"' {
				if quoted {
					if i+1 >= len(line) || line[i+1] != '"' {
						// end of quoted
						quoted = false
					} else {
						i++
						builder.WriteRune('"')
					}
				} else {
					// start of quoted
					quoted = true
				}
			} else {
				builder.WriteRune(line[i])
			}
		}
		// end of line
		if !quoted {
			fields = append(fields, builder.String())
			builder.Reset()
			if !handler(lineCount, fields) {
				return nil
			}
			fields = []string{}
		}
		// increase line count
		lineCount++
	}
	return sc.Err()
}

**Comment by zhenghaoz** [comment]
感谢，如果可以的话欢迎直接发起pull request哈，作者改的话比较慢

**Comment by amaaazing** [comment]
OK
