### ISSUE TITLE
gorse-master 启动成功，http:127.0.0.1:8088/  无法访问

### ISSUE THREAD

**Issue by Avey777** [zhenghaoz/gorse#255]
![图片](https://user-images.githubusercontent.com/35259040/132967425-7c14935e-a83e-463d-93b0-581fbd511318.png)

**Comment by brivadeneira** [comment]
Hello there, 
I still have this issue

**Comment by zhangzhenghao** [comment]
> Hello there, I still have this issue

Could you paste logs. Thx

**Comment by brivadeneira** [comment]
> > Hello there, I still have this issue
> 
> Could you paste logs. Thx

```
➜  gorse docker-compose up -d                               

gorse_mysql_1 is up-to-date
gorse_master_1 is up-to-date
gorse_worker_1 is up-to-date
gorse_redis_1 is up-to-date
gorse_server_1 is up-to-date
➜  gorse docker-compose start

Starting redis  ... done
Starting mysql  ... done
Starting worker ... done
Starting server ... done
Starting master ... done
➜  gorse wget http://127.0.0.1:8088/
--2021-11-15 23:02:54--  http://127.0.0.1:8088/
Connecting to 127.0.0.1:8088... failed: Connection refused.

```

**Comment by zhenghaoz** [comment]
> > > Hello there, I still have this issue
> > 
> > 
> > Could you paste logs. Thx
> 
> ```
> ➜  gorse docker-compose up -d                               
> 
> gorse_mysql_1 is up-to-date
> gorse_master_1 is up-to-date
> gorse_worker_1 is up-to-date
> gorse_redis_1 is up-to-date
> gorse_server_1 is up-to-date
> ➜  gorse docker-compose start
> 
> Starting redis  ... done
> Starting mysql  ... done
> Starting worker ... done
> Starting server ... done
> Starting master ... done
> ➜  gorse wget http://127.0.0.1:8088/
> --2021-11-15 23:02:54--  http://127.0.0.1:8088/
> Connecting to 127.0.0.1:8088... failed: Connection refused.
> ```

Could you paste logs insider Docker containers. Please use:
```bash
docker-compose logs master
```

**Comment by brivadeneira** [comment]
> ```shell
> ```shell
> docker-compose logs master
> ```
> 
> 
>     
>       
>     
> 
>       
>     
> 
>     
>   
>       
> ```

```
master_1  | {"level":"fatal","ts":1637064326.2296793,"caller":"gorse-master/main.go:53","msg":"failed to load config","error":"read /etc/gorse/config.toml: is a directory","stacktrace":"main.glob..func1\n\t/go/gorse/cmd/gorse-master/main.go:53\ngithub.com/spf13/cobra.(*Command).execute\n\t/go/pkg/mod/github.com/spf13/cobra@v0.0.7/command.go:842\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\t/go/pkg/mod/github.com/spf13/cobra@v0.0.7/command.go:943\ngithub.com/spf13/cobra.(*Command).Execute\n\t/go/pkg/mod/github.com/spf13/cobra@v0.0.7/command.go:883\nmain.main\n\t/go/gorse/cmd/gorse-master/main.go:70\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:255"}
```

Where should I put the toml file?

**Comment by zhenghaoz** [comment]
> > ```shell
> > ```shell
> > docker-compose logs master
> > ```
> 
> ```
> master_1  | {"level":"fatal","ts":1637064326.2296793,"caller":"gorse-master/main.go:53","msg":"failed to load config","error":"read /etc/gorse/config.toml: is a directory","stacktrace":"main.glob..func1\n\t/go/gorse/cmd/gorse-master/main.go:53\ngithub.com/spf13/cobra.(*Command).execute\n\t/go/pkg/mod/github.com/spf13/cobra@v0.0.7/command.go:842\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\t/go/pkg/mod/github.com/spf13/cobra@v0.0.7/command.go:943\ngithub.com/spf13/cobra.(*Command).Execute\n\t/go/pkg/mod/github.com/spf13/cobra@v0.0.7/command.go:883\nmain.main\n\t/go/gorse/cmd/gorse-master/main.go:70\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:255"}
> ```
> 
> Where should I put the toml file?

`config.toml` should in the same folder with `docker-compose.yaml`.

https://github.com/zhenghaoz/gorse/blob/45ac0f6105a84277e9e2e2157891bec7e197574c/docker/docker-compose.yml#L50

**Comment by brivadeneira** [comment]
> > > ```shell
> > > ```shell
> > > docker-compose logs master
> > > ```
> > 
> > 
> > ```
> > master_1  | {"level":"fatal","ts":1637064326.2296793,"caller":"gorse-master/main.go:53","msg":"failed to load config","error":"read /etc/gorse/config.toml: is a directory","stacktrace":"main.glob..func1\n\t/go/gorse/cmd/gorse-master/main.go:53\ngithub.com/spf13/cobra.(*Command).execute\n\t/go/pkg/mod/github.com/spf13/cobra@v0.0.7/command.go:842\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\t/go/pkg/mod/github.com/spf13/cobra@v0.0.7/command.go:943\ngithub.com/spf13/cobra.(*Command).Execute\n\t/go/pkg/mod/github.com/spf13/cobra@v0.0.7/command.go:883\nmain.main\n\t/go/gorse/cmd/gorse-master/main.go:70\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:255"}
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Where should I put the toml file?
> 
> `config.toml` should in the same folder with `docker-compose.yaml`.
> 
> https://github.com/zhenghaoz/gorse/blob/45ac0f6105a84277e9e2e2157891bec7e197574c/docker/docker-compose.yml#L50

```
Starting redis  ... done
Starting mysql  ... done
Starting worker ... done
Starting server ... done
Starting master ... error

ERROR: for master  Cannot start service master: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: rootfs_linux.go:76: mounting "/home/bibo/properati/gorse/config.toml" to rootfs at "/etc/gorse/config.toml" caused: mount through procfd: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type

```

**Comment by zhenghaoz** [comment]
@brivadeneira Does it help? https://stackoverflow.com/questions/45972812/are-you-trying-to-mount-a-directory-onto-a-file-or-vice-versa
