### ISSUE TITLE
One question about runFindUserNeighborsTask

### ISSUE THREAD

**Issue by deliangyang** [zhenghaoz/gorse#259]
This block will return the collection of item ids?

```go 
users := dataset.UserFeedback[userId] 
```

https://github.com/zhenghaoz/gorse/blob/7698ce7fe4aaa574a05af5d7570cf1ad24e3b2f0/master/tasks.go#L425-L435

**Comment by zhenghaoz** [comment]
This step speeds up neighbor searching. Only users have at least one common label or item are considered for distance computation.

**Comment by deliangyang** [comment]
Find users with the same feedback, Is there something wrong here?  Please review this PR #261

**Comment by zhenghaoz** [comment]
Thank you
