### ISSUE TITLE
add a swagger.yml 

### ISSUE THREAD

**Issue by lucmichalski** [zhenghaoz/gorse#280]
Hi @zhenghaoz ,

Hope you are all well !

I was wondering if you can push the swagger.yml file for the api specs ?

I d like to generate an api gateway for managing multi-tenancy based on the specs.

Cheers,
Luc Michalski

**Comment by zhangzhenghao** [comment]
There is already a JSON version of swagger spec at http://127.0.0.1:8087/apidocs.json. However, I don't know how to generate YAMl version spec by https://github.com/emicklei/go-restful-openapi.
