### ISSUE TITLE
/api/item/{item-id} expects int for item-id, but there should be string

### ISSUE THREAD

**Issue by PetrBezousek** [zhenghaoz/gorse#282]
**Gorse version**
gorse-server:latest

**Describe the bug**
Handler `/api/item/{item-id}` does not allow string ID, only int (see image below). I cannot use this handler because creating items allows string data type.

**To Reproduce**
Calling `/api/item/{item-id}` through the Swagger UI.

**Expected behavior**
API should accept string ID the same way it works for deleting items (there is a string data type).

**Additional context**
IMHO this line should change https://github.com/zhenghaoz/gorse/blob/90f882c51e3356c115a34e906784ae5e180db9f6/server/rest.go#L150
![](https://i.imgur.com/fMw7OYW.png)

**Comment by zhenghaoz** [comment]
This is a typo in documentation. Thank you @PetrBezousek.
