### ISSUE TITLE
gorse error in Docker container

### ISSUE THREAD

**Issue by deslum** [zhenghaoz/gorse#3]
```
goroutine 1 [running]:
xr/svd-cooker/vendor/github.com/zhenghaoz/gorse/core.init.0()
	/go/src/xr/svd-cooker/vendor/github.com/zhenghaoz/gorse/core/built_in.go:75 +0x2a
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x75be6a]
```

https://github.com/zhenghaoz/gorse/blob/master/core/built_in.go

```
func init() {
	usr, _ := user.Current()
	gorseDir := usr.HomeDir + "/.gorse"
	downloadDir = gorseDir + "/download"
	dataSetDir = gorseDir + "/datasets"
	TempDir = gorseDir + "/temp"
}

```

1. Need return err in user.Current()
2. Need create path without being tied to the user

**Comment by zhenghaoz** [comment]
Thanks for your feedback ^_^. Actually, I haven't considered the situation in Docker and I have limited knowledge about Docker. I'll try to fix it later.

**Comment by deslum** [comment]
With ENV USER root work

```
FROM scratch

ENV USER root

ADD test ./test
VOLUME ["/logs", "/models"]

CMD ["./test", "-log_dir", "logs"]
```

**Comment by deslum** [comment]
> Thanks for your feedback ^_^. Actually, I haven't considered the situation in Docker and I have limited knowledge about Docker. I'll try to fix it later.

It is enough to display an error. Then it's clear what's the matter.
