### ISSUE TITLE
Mixup of syncedChannel and pulledChan

### ISSUE THREAD

**Issue by nilansaha** [zhenghaoz/gorse#309]
Based on the code in the `worker.go` file I think [these](https://github.com/zhenghaoz/gorse/blob/master/worker/worker.go#L84-L85) variables are not used correctly across the codebase. Only `syncedChan` is used throughout. `pulledChan` is initialized but never used.

I think [this](https://github.com/zhenghaoz/gorse/blob/master/worker/worker.go#L267)  and [this](https://github.com/zhenghaoz/gorse/blob/master/worker/worker.go#L339)  should use `pulledChan`

**Comment by zhenghaoz** [comment]
You are RIGHT !!! 😂  Thanks a lot
