### ISSUE TITLE
关于Restful server 有一些问题。

### ISSUE THREAD

**Issue by davewang** [zhenghaoz/gorse#32]
如果用这个做个内容推荐，类似推特
实现的效果：用户每刷新一次，请求一次推荐，每次的推荐的内容不同。
根据用户的浏览点击和点赞来打分，把事实的数据同步给gorse（新发的推文，浏览量，点赞量打分更新等），
1.每一次请求出不同的推荐结果（已经推荐过的内容不会再推荐）？
2.是否可以控制每次最大推荐的数量（比如一次最多推荐20条条推文） ？

**Comment by zhenghaoz** [comment]
您好，您的想法很有道理，2的话已经实现了，但是1的话需要做一些修改，需要记录浏览过的但是没有被选中的内容，然后在展示之前排除掉，这就需要等待后续的实现了。

**Comment by davewang** [comment]
好的，谢谢！
还有个问题，这个数据变化需要重新训练模型吗？那么性能影响很大吧。

**Comment by zhenghaoz** [comment]
数据变化（新增数量超过一定阈值）会自动重新训练模型的哦

**Comment by davewang** [comment]
感觉全量用户做推荐cache有点浪费，建议加一个用户最后活跃时间，根据最近多少天以内活跃用户作cache更好些。那么item其实也应该有个时间戳，太旧的内容给用户推荐也没有太大的意义。

**Comment by zhenghaoz** [comment]
感谢您的建议：

1. 时间戳最新版本已经支持了，只要修改一下推荐的逻辑就好了
2. 至于不用用户cache大小不同的话，这个会略微麻烦一些
