### ISSUE TITLE
Feedback cannot be empty, Why?

### ISSUE THREAD

**Issue by LouisAldorio** [zhenghaoz/gorse#325]
Please answer these questions before submitting your issue. Thanks!

**Gorse version**
Go version 1.15.2

**Describe the bug**
One user must at least give one positive feedback and one neutral feedback, if not the collaborative won't work. The dashboard will display no feedback found.

But if all user in my application at least give one neutral feedback and one positive feedback , it will train the collaborative filtering model.

this does not make any sense , we cannot force a user to give positive feedback to our application. Please fix this

**To Reproduce**
Just empty the feedback table. And your will reproduce the error

**Expected behavior**
Even at empty state of the feedback table. The dashboard does not throw "no feedback error"

**Comment by zhenghaoz** [comment]
Hi, @LouisAldorio. Do you mean that Gorse should recommend when there is no feedback?

**Comment by LouisAldorio** [comment]
no @zhenghaoz , but atleast do not force any all user to read at least one item and give feedback to atleast one item. If there is new user in my db and i add  to the gorse db BY API. But the user still has nott read and like any item. than the gorse will just return no feedback found and will not train for the collaborative filtering model on the next period.

**Comment by zhenghaoz** [comment]
> no @zhenghaoz , but atleast do not force any all user to read at least one item and give feedback to atleast one item. If there is new user in my db and i add to the gorse db BY API. But the user still has nott read and like any item. than the gorse will just return no feedback found and will not train for the collaborative filtering model on the next period.

I see. We will try to solve this problem in the future release.
