### ISSUE TITLE
添加新数据是否需要重新训练模型

### ISSUE THREAD

**Issue by APlaceCalled-you** [zhenghaoz/gorse#34]
我打算在go的项目中使用您的包来进行完成推荐的部分，但文档中这部分却很少我未找到我需要的资料。在这里冒昧询问，希望可以得到您的回复
1. 我在加载数据之后，可以得到 相关的排行数据，如果产生了新的数据，是不是要重新计算这个模型，包括之前的旧数据；
// 数据添加之后是否需要重新执行下面这个过程
data := core.LoadDataFromCSV("test/recommend/games.csv", ",", true)
    train, _ := core.Split(data, 0.2)
    // Create model
    knn := model.NewKNNImplicit(base.Params{
        base.NFactors:   10,
        base.Reg:        0.01,
        base.Lr:         0.05,
        base.NEpochs:    100,
        base.InitMean:   0,
        base.InitStdDev: 0.001,
    })
    knn.Fit(train, nil)
    rank, _ := core.Neighbors(data, "222900", 10, engine.LoadSimilarity("msd"))

**Comment by zhenghaoz** [comment]
如果你自己写代码的话是需要重新训练模型的呢:smile:
