### ISSUE TITLE
feedback_type该怎么设置

### ISSUE THREAD

**Issue by dschain** [zhenghaoz/gorse#353]
麻烦问下，商品推荐时，feedback_type该怎么设置，看文档有些绕，不太理解。电商有展示、浏览、停留、收藏、加购、下单、支付等等类型。有模板最好，对应用有帮助。

**Comment by zhangzhenghao** [comment]
如果觉得文档不直观，可以阅读微信公众号上的中文文档哈：https://mp.weixin.qq.com/s/Cgf-e31YTVd2l9LKUXBk0w

**Comment by dschain** [comment]
3q
