### ISSUE TITLE
Gorse suitable for a job-ads recommender app ?

### ISSUE THREAD

**Issue by superseby2** [zhenghaoz/gorse#357]
Hello, 

I am  building a job board app and are evaluating recommenders. 
Would gorse work well in this field ? 

- items would be our offers 
- labels being the criteria of the ad
- users would be people looking for a job and  adding their feedback from the list of available jobs 

The only issue I am seeing right now is how to handle cold-start. Is there some ways to make use of user properties (user has a profile with properties that could match criterias)?

Could you advise on  whether gorse might be a good fit and pointers to handle cold-start?

Thanks for your time (and for gorse!)

**Comment by zhangzhenghao** [comment]
Unfortunately, Gorse is unable to handle pure cold-start  recommendation. Similar items could be recommended to users with few feedback. However, Gorse cannot generate personalized recommendation for users without any feedback. It only recommend latest or popular items to new users without any feedback.

**Comment by superseby2** [comment]
Thanks for taking the time! I guess we would need to tackle our problem differently then.
