### ISSUE TITLE
Use environment variables in YAML config file

### ISSUE THREAD

**Issue by guiscaranse** [zhenghaoz/gorse#358]
**Is your feature request related to a problem? Please describe.**
Right now there isn't an easy way to change the DB or Redis settings without having to manually edit the config file. This is particular annoying when using the docker images as this requires to rebuild the images bundling the new config file.

**Describe the solution you'd like**
A way to reference an environment variable on the config file.

**Describe alternatives you've considered**
- Bundling the modified YAML file on the docker image.

**Comment by zhangzhenghao** [comment]
Good idea. This feature is easy to be implemented via [viper](https://github.com/spf13/viper).

**Comment by zhenghaoz** [comment]
There have been several variables exported:

https://github.com/zhenghaoz/gorse/blob/0f711495361578276074d893a9154e5db46a026f/config/config.go#L268-L277

Feel free to export more variables via pull requests.
