### ISSUE TITLE
希望restful api 能增加分页功能

### ISSUE THREAD

**Issue by sndwow** [zhenghaoz/gorse#37]
首先很感谢作者分享此项目，特别是提供了http方式可以简便的进行操作。

但目前发现api不支持游标和分页，只支持number进行获取，在使用过程中有诸多不便。
希望能增加分页功能，谢谢

**Comment by sndwow** [comment]
#27 不好意思，才发现有相同的issues

**Comment by zhenghaoz** [comment]
我有空修一下哈

**Comment by zhenghaoz** [comment]
已经进入release-0.2分支哈 #47
