### ISSUE TITLE
Some QueryParameter should be PathParameter on Swagger

### ISSUE THREAD

**Issue by europaer** [zhenghaoz/gorse#404]
This is just an example but there a few more:

https://github.com/zhenghaoz/gorse/blob/e3754c6e98e9a2e6e277db29a841eca0ce6ceecd/server/rest.go#L388

**Comment by zhangzhenghao** [comment]
There are some typos. Could you help to fix them? Otherwise, I will fix it later.😁

**Comment by europaer** [comment]
I have sent a PR https://github.com/zhenghaoz/gorse/pull/405

**Comment by europaer** [comment]
Kudos for the amazing recommender library!

**Comment by zhenghaoz** [comment]
> Kudos for the amazing recommender library!

Thanks :smile:
