### ISSUE TITLE
希望能多写一些使用的例子与说明

### ISSUE THREAD

**Issue by xinjiayu** [zhenghaoz/gorse#41]
说明文档内容太少了。希望能多增加一些使用的例子与说明。特别是结合应用场景的详细使用过程。谢谢啊

**Comment by zhenghaoz** [comment]
例子主要是那个游戏推荐系统哈，文档的话目前我在开发0.2版本，所以暂时不会更新哒

**Comment by zhenghaoz** [comment]
目前已经完成了还算完整的文档：https://docs.gorse.io/ ，和一个demo：https://github.com/zhenghaoz/gitrec 。
如果还有其他问题，欢迎咨询。
