### ISSUE TITLE
Prevent recommending an item for an user who provided feedback

### ISSUE THREAD

**Issue by abdullahcanakci** [zhenghaoz/gorse#49]
I have been trying the gorse with bpr model to recommend content to users, whom have option to give feedback which are fed into gorse.

I'm using gorse as standalone web server and accessing with it's own apis.

What I'm trying to accomplish is preventing the engine from recommending content the user already provided feedback. Bu I have looked both into the docs and the code but nothing really looked like what I wanted. There is somewhat related #33 but it recommends an entry only once and never again.

Is there any way to accomplish what I want.

**Comment by zhenghaoz** [comment]
Hi. @abdullahcanakci 

If a user's feedback have been added to gorse, they won't be recommended to this user anynore. Actually, this logic has been implemented in gorse by default. I don't know if this logic meet your expectation :D

**Comment by abdullahcanakci** [comment]
Thank you,
I have been using, and I thought it was an error on somewhere but after I rebuild my users, feedback and etc I still have the same issue. 
I am accessing `/recommends/1/` and receive a list like below
```json
[
 {
  "ItemId": "44",
  "Popularity": 1,
  "Timestamp": "2020-08-10T00:00:00Z",
  "Score": 1
 }
...
```

After that I send a feedback like below
```bash
curl -X PUT -H 'Content-Type: application/json' url:8888/feedback -d '[{"UserId":"1","ItemId":"44","Rating":1}]'
```
After this I assume Item 44 would be no longer visible but consecutive request are all responds with item 44 included.

Is there anything I'm missing?
Also I'm including my db and config if it would help.

[gorse_db_config.zip](https://github.com/zhenghaoz/gorse/files/5051718/gorse_db_config.zip)

**Comment by zhenghaoz** [comment]
Okay. I find the problem. That is, in lastest implementation, the feedback will be ignored util next model update. But now I realized it would be better to remove them from recommendations once they are submitted. I will try to fix it. Thanks for your feedback.

**Comment by abdullahcanakci** [comment]
Thank you, much appreciated :smile:

**Comment by mehmetcansahin** [comment]
Hello, are there any updates on the issue?

**Comment by zhenghaoz** [comment]
> Hello, are there any updates on the issue?

This feature has been added in branch release-0.2 ;D

**Comment by mehmetcansahin** [comment]
Thank you. ❤️

**Comment by abdullahcanakci** [comment]
> > Hello, are there any updates on the issue?
> 
> This feature has been added in branch release-0.2 ;D

Thank you very much ❤️
