### ISSUE TITLE
Using Gorse in Python

### ISSUE THREAD

**Issue by 123nishant** [zhenghaoz/gorse#56]
HI Team,

I want to use Gorse in python. 

Do you have any suggestions or steps ?

**Comment by 123nishant** [comment]
Couldn't find much online

**Comment by zhenghaoz** [comment]
It depends the meaning of "use". We can use gorse as a RESTful service. In this situation, a python application can use gorse by HTTP communication. However, we can't call functions directly except using some magic.

**Comment by 123nishant** [comment]
Thanks !
