### ISSUE TITLE
Unknown model knn_implicit

### ISSUE THREAD

**Issue by biganashvili** [zhenghaoz/gorse#57]
After running the test 
`gorse test knn_implicit --load-csv games.csv --csv-sep ',' --eval-precision --eval-recall --eval-ndcg --eval-map --eval-mrr` 
I am getting an error like this:
`Unknown model knn_implicit`

I tried both, with -tags='avx2' and without 
gorse version
0.1.3

**Comment by zhenghaoz** [comment]
`knn_implicit` has been elimited. This issues has to been closed.
