### ISSUE TITLE
请问readme里的数据导入那的 导入数据的格式有什么要求吗？

### ISSUE THREAD

**Issue by a807904790** [zhenghaoz/gorse#63]

**Comment by zhenghaoz** [comment]
要求user_id, item_id, rating这样 :D

**Comment by a807904790** [comment]
请问下rating是代表什么？

**Comment by zhenghaoz** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    原来代表评分，但是现在只有排序模型了，评分没用了，留空就好了哈，后面会删掉的~
    
        
            
        
    
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                zhangzhenghao
                            
                    
                        
                            
                                    zhangzhenghao@hotmail.com
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    在2020年11月25日 19:50，a807904790<notifications@github.com> 写道： 




请问下rating是代表什么？



—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by a807904790** [comment]
user_id跟item_id是一对多吗？ 可以理解为用户的商品的一次点击行为吗？

**Comment by zhenghaoz** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    应该是多对多的，点击也是可以的，但是点击对于用户的“喜欢”其实不够强烈，最好是点赞/差不多完整观看什么的 :D
    
        
            
        
    
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                zhangzhenghao
                            
                    
                        
                            
                                    zhangzhenghao@hotmail.com
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    在2020年11月25日 19:55，a807904790<notifications@github.com> 写道： 




user_id跟item_id是一对多吗？ 可以理解为用户的商品的一次点击行为吗？



—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by a807904790** [comment]
哦哦对，是多对多，多谢答疑

**Comment by a807904790** [comment]
我看api里有insert接口，这个系统是实时的吗？

**Comment by a807904790** [comment]
> font{ line-height: 1.6; } ul,ol{ padding-left: 20px; list-style-position: inside; } 应该是多对多的，点击也是可以的，但是点击对于用户的“喜欢”其实不够强烈，最好是点赞/差不多完整观看什么的 :D zhangzhenghao zhangzhenghao@hotmail.com 签名由 网易邮箱大师 定制 在2020年11月25日 19:55，a807904790<notifications@github.com> 写道： user_id跟item_id是一对多吗？ 可以理解为用户的商品的一次点击行为吗？ —You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.
