### ISSUE TITLE
关于要清除item的需求

### ISSUE THREAD

**Issue by jacoblai** [zhenghaoz/gorse#65]
在商业应用中，一些应用，如作品已发布到gorse,然后异步鉴黄作品后，作品没有通过鉴黄，需要在gorse中清除数据。这个功能如何做？谢谢！

**Comment by zhenghaoz** [comment]
你好，删除item的功能已经在feat/dustributed中实现，后续会合并到release-0.2中，由于改动较大，master上代码为老版本不打算做维护了，所以要等0.2版本了哈 :D

**Comment by jacoblai** [comment]
好的。谢谢
