### ISSUE TITLE
insert feedback新的用户后，调推荐的接口，提示用户不存在

### ISSUE THREAD

**Issue by a807904790** [zhenghaoz/gorse#67]

**Comment by zhenghaoz** [comment]
应该是没有来得及生成推荐结果，一般需要等待一下~

**Comment by a807904790** [comment]
周期是多长呢？ 有几天了，feedback接口倒是能看到记录

**Comment by zhenghaoz** [comment]
有没有日志看看？有可能在什么环节出了问题

**Comment by a807904790** [comment]
bucket not found
2020/12/11 10:38:52 000 not found
2020/12/11 16:02:14 000 not found

**Comment by zhenghaoz** [comment]
有完整一点的日志吗，最好是导入数据之后开始的，我们需要看看到底它到底有没有更新过

**Comment by a807904790** [comment]
2020/12/07 22:21:17 open asd: The system cannot find the file specified.
2020/12/07 22:21:17 connect to database: C:\Users\16593/.gorse/gorse.db
2020/12/07 22:21:17 start model updater
2020/12/07 22:21:17 start a server at 127.0.0.1:8080
2020/12/07 22:24:05 bucket not found
2020/12/07 23:40:18 invalid character '\'' looking for beginning of value
2020/12/07 23:40:59 invalid character 'U' looking for beginning of object key string
2020/12/08 12:54:31 invalid character '\'' looking for beginning of value
2020/12/08 16:56:41 invalid character '\'' looking for beginning of value
2020/12/08 19:56:09 000 not found
2020/12/08 19:56:19 0000 not found
2020/12/08 19:58:30 000 not found
2020/12/08 20:06:33 000 not found
2020/12/08 20:13:11 000 not found
2020/12/08 20:46:55 json: cannot unmarshal string into Go struct field Feedback.Feedback of type float64
2020/12/08 20:59:00 json: cannot unmarshal string into Go struct field Feedback.Feedback of type float64
2020/12/11 10:38:32 bucket not found
2020/12/11 10:38:52 000 not found
2020/12/11 16:02:14 000 not found

**Comment by zhenghaoz** [comment]
没有落盘，看来我后面还是要让日志能够落盘。`2020/12/07 22:21:17 start model updater`表示开始了模型更新，但是后面发生了啥就不知道了，感觉是哪里出问题了

**Comment by a807904790** [comment]
我看代码貌似 insert feedback的时候没有插入“recommends”这个桶？ 然后推荐的时候是去这个桶拿item？

**Comment by zhenghaoz** [comment]
recommends是由推荐算法插入的哈，所以应该是推荐结果生成的时候出了问题

**Comment by a807904790** [comment]
哦哦，是我的操作不对吗？

**Comment by zhenghaoz** [comment]
加一下我的微信吧：zhenghaoz，我需要更多信息>_<
