### ISSUE TITLE
请问能推荐相似的电影吗？

### ISSUE THREAD

**Issue by zichen8552** [zhenghaoz/gorse#9]
比如在电影详情页，推荐一些相似的电影，或者是大家都爱看的且与当前这一部相关的。
我理解的是现在是只能推荐给用户他可能会喜欢的电影。
对这些算法不太了解，非常感谢作者的付出。

**Comment by zhenghaoz** [comment]
很感谢您对于本项目的支持。像您这种需求，最简单的方法就是通过两个电影看过的用户或者电影本身信息来计算相似度，也就类似KNN里面计算相似度的办法，然后推荐相似电影。我以后也会加入这个功能，但是不会很快😁

**Comment by zhenghaoz** [comment]
在算法层面，我已经实现了这个功能（ 5c9dd8003cc5c2991aac3302cccf2dd858525055），但是离应用有些距离，后续还要对相关数据结构和操作进行优化。

**Comment by zichen8552** [comment]
非常感谢，厉害了，给你点赞。

**Comment by zhenghaoz** [comment]
现在算是完全实现了，根据共同看过的用户数量进行推荐
- API：https://gorse.readthedocs.io/en/latest/usage/server/api.html#get-similar-items
- Demo：https://steamlens.gorse.io/item/8870
可以发现给定《生化奇兵：无限》是可以推荐出《生化奇兵》和《生化奇兵2》的
